[package]
name = "avatar-bot"
authors = ["南浦月 <nanpuyue@gmail.com>"]
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.2"
lazy_static = "1.4.0"
pretty_env_logger = "0.4.0"
reqwest = "0.11.10"
rsmpeg = "0.9.0"
teloxide = { version = "0.9.1", features = ["auto-send", "macros"] }
tokio = { version = "1.19.1", features = ["macros", "rt-multi-thread"] }
webp = "0.2.2"
webpage = { version = "1.4.0", default-features = false }
