[package]
name = "avatar-bot"
authors = ["南浦月 <nanpuyue@gmail.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
lazy_static = "1.4.0"
log = "0.4.16"
pretty_env_logger = "0.4.0"
reqwest = "0.11.10"
rsmpeg = "0.7.0"
teloxide = { version = "0.5.3", features = ["auto-send", "macros"] }
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
webp = "0.2.2"
webpage = { version = "1.4.0", default-features = false }
