[package]
name = "avatar-bot"
authors = ["南浦月 <nanpuyue@gmail.com>"]
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
lazy_static = "1.4.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
rsmpeg = "0.6.0"
teloxide = { version = "0.5.2", features = ["auto-send", "macros"] }
tokio = { version = "1.10.1", features = ["macros", "rt-multi-thread"] }
webp = "0.1.3"
