[package]
name = "avatar-bot"
authors = ["南浦月 <nanpuyue@gmail.com>"]
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.4"
lazy_static = "1.4.0"
pretty_env_logger = "0.4.0"
reqwest = "0.11.12"
rsmpeg = "0.12.0"
teloxide = { version = "0.11.0", features = ["macros"] }
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
webpage = { version = "1.4.0", default-features = false }
